#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs



singularity exec docker://brainlife/mne:1.0.2 python3 main.py

cat << EOF > product2.json
{
    "brainlife": [
       {
         "type": "image/png",
	       "name": "Ica components",
         "base64": "$(base64 -w 0 out_figs/ica.png)"
       }
]
}
EOF

jq -s '{ brainlife: map(.brainlife[0]) }' product*.json > product.json

rm -rf product1.json product2.json
